//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathieuShopKornilova.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.MasterService = new HashSet<MasterService>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> LastEdit { get; set; }
        public Nullable<int> CollectionId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Collection Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterService> MasterService { get; set; }
    }
}
